apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck
  namespace: common-services
  labels:
    app: rundeck
spec:
  storageClassName: nfs-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck2
  namespace: common-services
  labels:
    app: rundeck
spec:
  storageClassName: nfs-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

